### ISSUE TITLE
Abas Frentes de Atuação

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/alianca-residuos-zero-theme#1]
@matheusgimenez aqui vamos usar aquela lógica de sub-pages (da página mãe Frentes de Atuação) e adicionar um loop criando essas abas, com excerpt e thumb.

Veja o print, e o que já está pronto em brasaWP/alianca-residuo-zero/

![__1](https://cloud.githubusercontent.com/assets/1918474/7451874/6f20b3d0-f22c-11e4-9453-40194ddb8d30.jpg)

O layout é esse abaixo, mas se preocupe mais com a funcionalidade que eu arremato o CSS:

![residuozero -layout_homea-v2](https://cloud.githubusercontent.com/assets/1918474/7451887/93a42908-f22c-11e4-9375-81570ac96d3d.jpg)

**Comment by matheusgimenez** [comment]
feito no ultimo commit
