### ISSUE TITLE
Página Boas Práticas posts sem o "Leia Mais"

### ISSUE THREAD

**Issue by diogosp** [brasadesign/alianca-residuos-zero-theme#29]
Na página:
http://residuozero.org.br/boas-praticas/

As postagens estão sem o botão LEIA MAIS

@everaldomatias @matheusgimenez

**Comment by LuwkasLima** [comment]
![image](https://cloud.githubusercontent.com/assets/5949986/8915083/7c166e94-3468-11e5-8b24-383125b1435c.png)

**Comment by diogosp** [comment]
valeu @LuwkasLima não havia reparado mesmo que estava ali. É um problema de CSS então, correto?

**Comment by everaldomatias** [comment]
Resolvido.
