### ISSUE TITLE
Agenda de Eventos

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/alianca-residuos-zero-theme#3]
@matheusgimenez deixei pronto o HTML dessa listagem de itens da Agenda (depois faço issues da single ou modal disso).

Veja isso em brasaWP/alianca-residuo-zero/o-que-e/

Gostaria de já estruturar algo para esse CPT daquela forma que possamos reaproveitar em outros projetos de forma fácil.

Imagino algo como uma pasta no /inc/agenda com:

• agenda.php
• functions-agenda.php
• style-agenda.css
• main-agenda.css
....

O que acha?

![_1](https://cloud.githubusercontent.com/assets/1918474/7534682/2c620646-f553-11e4-9bb8-aa6a97bbec08.jpg)

**Comment by matheusgimenez** [comment]
Eu fiz, mas não pensei em reuso de codigo, pelo menos não nesse projeto. Tô com umas ideias na cabeça pra isso, mas ainda falta coisas pra fechar, sacas?
