### ISSUE TITLE
Area PARTICIPE em Noticias esta com CSS quebrado

### ISSUE THREAD

**Issue by LuwkasLima** [brasadesign/alianca-residuos-zero-theme#30]
Pessoal, tem algum problema rolando com o CSS da area PARTICIPE dentro da pagina Noticias:

![image](https://cloud.githubusercontent.com/assets/5949986/9044342/9c9e25ac-39e1-11e5-8ad6-bfb355b355af.png)

**Comment by LuwkasLima** [comment]
Achei tambem na pagina Contato:

![image](https://cloud.githubusercontent.com/assets/5949986/9044402/03256fe2-39e2-11e5-9f14-eb313cabbd90.png)

**Comment by diogosp** [comment]
A Aliança acabou de me enviar o mesmo print!

![css quebrado - agenda page noticias](https://cloud.githubusercontent.com/assets/5107285/9047747/4860c142-3a0a-11e5-8c0e-b1d27bb07e9a.png)

**Comment by everaldomatias** [comment]
Resolvido.
