### ISSUE TITLE
Home Alternativa - Page Template

### ISSUE THREAD

**Issue by everaldomatias** [brasadesign/alianca-residuos-zero-theme#5]
@matheusgimenez programa isso como um Page Template chamado "Home Alternativa".

Esse template terá:
O mini-header que já temos programado;
Slider (pode ser o da Brasa), observe que ele tem seta apenas na direita e os bullets;
CPT Ações com descrição via Options Kirki e link para o archive;
Sub-footer que também já temos programado.

Qualquer dúvida é só chamar.

![residuozero -layout_homeb-v1](https://cloud.githubusercontent.com/assets/1918474/7718391/15dafdce-fe86-11e4-8c85-b07344d424a8.jpg)

**Comment by matheusgimenez** [comment]
feito no ultimo commit
